
// buildStack() gathers information about current stackframes/scopes
// structured as follows (using nested named lists):

import { DebugProtocol } from './DebugProtocol';

import { LazyTree } from './lazyTree';

import { RValue, REnvironment, RFunction, RCall, RNULL, RList, RVector } from './RTypes';


export declare module StackTree {
    
    
    interface Content extends LazyTree.Content {
        nodeType: ('Stack'|'Frame'|'Scope'|'Variable');
    }
    
    interface ChildrenArgs extends LazyTree.ChildrenArgs {
        nodeType: ('Stack'|'Frame'|'Scope'|'Variable');
    }
    
    interface ContentArgs extends LazyTree.ContentArgs {
        nodeType: ('Stack'|'Frame'|'Scope'|'Variable');
    }
    
    type varInfos = varInfo[];
    
    interface Source extends DebugProtocol.Source {
        name: string;
        path: string;
        sourceReference: number;
        line: number;
        endLine: number;
        column: number;
        endColumn: number;
        srcbody: string;
        isFile: boolean;
        presentationHint?: 'normal' | 'emphasize' | 'deemphasize';
    }
    
    
    interface Stack extends Content {
        totalFrames?: number,
    }
    
    interface StackFrame extends DebugProtocol.StackFrame, Content {
        // set name = '' + id
        variablesReference: number;
        frameIdR: number;
    }
    
    interface Scope extends DebugProtocol.Scope, Content {
        name: string;
        rValue: REnvironment;
        variablesReference: number;
        setInfo?: SetInfo; // sensible here?
    }
    
    interface SetInfo {
        setter?: RValue, // e.g. quote(v[1,]), sufficient for non-root elements
        
        expression?: RValue; //only required for root element
        environment?: REnvironment; // only required for root element
    }
    
    interface Variable extends MinimalVariable, DebugProtocol.Variable, Content {
        name: string;
        value: string;
        type: string;
        evaluateName: string;
        
        setter?: RValue;
        setInfo?: SetInfo;
        
        hasChildren: boolean;
        rValue: RValue;
        
        variablesReference: number;
    }
    
    interface MinimalVariable {
        name: string;
        rValue: RValue;
        
        setter?: RValue;
        setInfo?: SetInfo;
    }
    
    type ChildVarFunction = (rValue: RValue) => MinimalVariable[];
    
    interface varInfo {
        name: string;
        doesApply: ((v: RValue) => boolean);
        childVars?: ChildVarFunction | MinimalVariable[];
        customAttributes?: ChildVarFunction | MinimalVariable[];
        internalAttributes?: ChildVarFunction | MinimalVariable[];
        hasChildren?: ((v:RValue) => boolean) | boolean;
        toString?: ((v:RValue) => string) | string;
        type?: ((v:RValue) => string) | string;
        includeAttributes?: ((v:RValue) => boolean) | boolean;
        evaluateName?: ((v:RValue) => string) | string;
    }
    
    function getSource(call?: RCall, frameIdR?: number): Source;
    
    
    function _vsc_buildStack(): LazyTree.NodeId;
    
    
    function buildStack(args: stackArgs): {
        contentContent: Stack;
        childrenArgs: FramesArgs;
    };
    function gatherFrames(args: FramesArgs): {
        contentArgs: FrameArgs;
        // childrenArgs: ScopesArgs; // generated by buildFrame()
    }[]
    
    function buildFrame(args: FrameArgs): {
        contentContent: StackFrame;
        childrenArgs: ScopesArgs;
    }
    
    function gatherScopes(args: ScopesArgs): {
        contentArgs: ScopeArgs;
        // childrenArgs: VariablesArgs; // generated by buildVariable()
    }[]
    
    function buildVariable(args: VariableArgs): {
        contentContent: Variable;
        childrenArgs: VariablesArgs;
    };
    function gatherVariables(args: VariablesArgs): {
        contentArgs: VariableArgs;
        // childrenArgs: VariablesArgs; // generated by buildVariable()
    }[]
    
    
    interface stackArgs extends ContentArgs, FramesArgs {
    }
    
    interface FramesArgs extends ChildrenArgs {
        topFrame: REnvironment;
        skipFromTop?: number;
        skipFromBottom?: number;
        isError: boolean;
        forceDummyStack?: boolean;
        dummyFile?: string;
    }
    
    interface FrameArgs extends ContentArgs {
        frameIdR: number;
        frameIdVsc: number;
        dummyFile?: string;
    }
    
    interface ScopesArgs extends ChildrenArgs {
        firstenv: REnvironment;
        lastenv: REnvironment;
    }
    
    interface VariableArgs extends ContentArgs {
        minVar: MinimalVariable;
    }
    
    interface ScopeArgs extends VariableArgs {
    }
    
    interface VariablesArgs extends ChildrenArgs {
        rValue: RValue;
    }
    
}