# This function retrieves the input completions generated by utils::XXX
# Is the same as used when e.g. pressing 2xTAB in the console
# Is a bit hacky, but seems to work fine
# Currently has some advantages over 'our' version, which should be fixed in the future
getCompletionsFromUtils <- function(text, column, line){
  # prepare text
  text <- gsub('\r\n', '\n', text) # clean newLines
  lines <- strsplit2(text, '\n') # split into lines
  text <- lines[line] # select correct line

  if(column>1){
    text <- substr(text, 1, column-1)
  }

  # assign current text and cursor position to (utils:::.CompletionEnv)
  utils:::.assignLinebuffer(text)
  utils:::.assignEnd(column)

  # call completion functions
  # arguments were assigned to env beforehand
  token <- utils:::.guessTokenFromLine()
  utils:::.completeToken()
  completions <- utils:::.retrieveCompletions()

  # logCat('Token: ', token, ' - end: ', column, ' - text: ', text, ' - completions:', length(completions), '\n', sep='')

  # return
  # (moving function parameters, e.g. 'a=' to the top of the sorted list)
  targets <- lapply(completions, function(comp){
    sortText <- comp
    lastChar <- substr(comp, nchar(comp), nchar(comp))
    if(nchar(lastChar)>0 && lastChar=='='){
      sortText <- paste0(' ', sortText)
    }
    list(
      label = comp,
      length = nchar(token),
      sortText = sortText
    )
  })
  return(targets)
}
strsplit2 <- function(x, split){
    # add arbitrary character to the end:
    if(split=='_'){
        x <- paste0(x, '*')
    } else{
        x <- paste0(x, '_')
    }
    # apply strsplit:
    v <- strsplit(x, split)[[1]]
    # remove last character:
    w <- v[length(v)]
    w <- substr(w, 1, nchar(w)-1)
    v[length(v)] <- w
    # return:
    v
}
